version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: debug
    image: coding-challenge/app:latest
    container_name: app
    entrypoint: ["tini", "--", "/usr/local/bin/docker-php-entrypoint"]
    command: ['php-fpm']
    stop_signal: SIGTERM
    restart: unless-stopped
    tty: true
    user: root
    env_file: .env
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      API_DOMAIN: localhost
      DB_CONNECTION: mysql
      LOG_CHANNEL: stack
      APP_LOG_LEVEL: debug
      APP_ENV: local
      APP_DEBUG: 'false'
      APP_URL: http://localhost
    working_dir: /var/www
    networks:
      - backend
    volumes:
      - ./:/var/www
      - ./config/logging-local.php:/var/www/config/logging.php
      - ./docker/php/php_debug.ini:/usr/local/etc/php/php.ini

  webserver:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: core
    image: coding-challenge/web:latest
    container_name: webserver
    restart: unless-stopped
    environment:
      PHP_APP_HOST: 'app:9000'
      RESOLVER: 127.0.0.11
    tty: true
    ports:
      - "80:80"
    networks:
      - backend
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/default.conf.template:/etc/nginx/templates/default.conf.template

networks:
  backend:
    external:
      name: backend
